"""empty message

Revision ID: 5450e3fd10a2
Revises: c78457db3d02
Create Date: 2021-08-05 21:12:16.491604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5450e3fd10a2'
down_revision = 'c78457db3d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'posted')
    # ### end Alembic commands ###
