"""empty message

Revision ID: 6964ac905fa0
Revises: 5450e3fd10a2
Create Date: 2021-08-05 21:24:42.621762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6964ac905fa0'
down_revision = '5450e3fd10a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('post', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sandbox', 'author_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sandbox', 'author_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('post', 'author_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
