"""empty message

Revision ID: 91caf5c4592e
Revises: f8dfc380d115
Create Date: 2021-08-12 22:02:33.308054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91caf5c4592e'
down_revision = 'f8dfc380d115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('author_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('post_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['post_uuid'], ['post.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('comment_like',
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('comment_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_uuid'], ['comment.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'comment_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like')
    op.drop_table('comment')
    # ### end Alembic commands ###
