"""empty message

Revision ID: eb5d20f606f6
Revises: 91caf5c4592e
Create Date: 2021-08-13 21:41:47.609320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb5d20f606f6'
down_revision = '91caf5c4592e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_exercise',
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'module_name', 'block_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_exercise')
    # ### end Alembic commands ###
