"""empty message

Revision ID: f8acfb5a060f
Revises: eb5d20f606f6
Create Date: 2021-08-13 22:21:35.739574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8acfb5a060f'
down_revision = 'eb5d20f606f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_exercise', sa.Column('module_id', sa.String(), nullable=False))
    op.drop_column('module_exercise', 'module_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_exercise', sa.Column('module_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('module_exercise', 'module_id')
    # ### end Alembic commands ###
